server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
      - id: exchange_rates_data_few_currencies
        uri: http://localhost:8080
        predicates:
        - Path=/exchange_rates_data_few_currencies/{access_Key}
               
      - id: exchange_rates_by_date
        uri: http://localhost:8080
        predicates:        
        - Path=/exchange_rates_by_date/{accessKey}/{date}
        
      - id: exchange_rates_data_all_currencies
        uri: http://localhost:8080
        predicates:        
        - Path=/exchange_rates_data_all_currencies/{accessKey}
      
      - id: exchange_rates_details_by_date
        uri: http://localhost:8080
        predicates:        
        - Path=/exchange_rates_details_by_date/{date}
        
      - id: exchange_rates_in_bwt_dates
        uri: http://localhost:8080
        predicates:        
        - Path=/exchange_rates_in_bwt_dates/{fromDate}/{toDate}      
        
        
        
        
        
        
        
