server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
      - id: exchange_Rates_Data_Few_Currencies
        uri: http://localhost:8080
        predicates:
        - Path=/exchange_Rates_Data_Few_Currencies/{access_Key}
       
        
        
        
        
        
